apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample-app
        image: codefob.azurecr.io/hello-world:latest
        ports:
        - containerPort: 80